### ISSUE TITLE
store size_t in a variant ?

### ISSUE THREAD

**Issue by SuperFola** [mpark/variant#40] opened 2018-02-04 15:54 UTC
Hi,

I am trying to store size_t as well as int64_t, double, bool, string in a variant. Storing the 4 last types work fine, but I get a bad_variant_access when trying to get/set the size_t with this code  : 

```cpp
#include <iostream>
#include <cstdint>
#define MPARK_EXCEPTIONS
#include <mpark/variant.hpp>

using namespace std;  // i know it's bad, it's just for testing

int main()
{
    mpark::variant<int64_t, double, bool, string, size_t> v;
    mpakr::get<size_t>(v) = 15;  // right there
    return 0;
}
```

*edit : updating code to fix compile errors*

**Comment by SaadAttieh** [comment] 2018-02-04 17:30
There are some compile errors in your code.  After  making changes such that it compiles, your issue becomes clear.  Here is some working code with a comment that should show your problem.  
#include <cstdint>
#include <iostream>
#define MPARK_EXCEPTIONS
#include "mpark/variant.hpp"

using namespace std;  // i know it's bad, it's just for testing

int main() {
  mpark::variant<int64_t, double, bool, string, size_t> v;
  // v is not assigned to size_t here, so you cannot call mpark::get
  v.emplace<size_t>(0);
  //now it is correctly assigned to type size_t
  mpark::get<size_t>(v) = 15;
  return 0;
}
  
If the type of x, where x is the value you are assigning v to is convertible to only one of the types in v, you would be able to simply write, v = x.  However, this is not possible when you have multiple int types in the same variant so I had to use emplace instead, hence being explicit about the type.

**Comment by SuperFola** [comment] 2018-02-04 21:25
Even this way, I am still getting a `bad_variant_access` :/

**Comment by mpark** [comment] 2018-02-05 06:15
@SuperFola: what configuration are you using?
@SaadAttieh's snippet works fine for me: https://wandbox.org/permlink/GFYehONmvuc7cByX

**Comment by SuperFola** [comment] 2018-02-05 16:33
I am using gnu gcc (mingw 4.8), with `-Wall -std=c++14 -g` on Windows (I want to add that I had to add the define `MPARK_EXCEPTIONS` to be able to see the error, otherwise I would just get a `terminate without an active exception`).

**Comment by mpark** [comment] 2018-02-10 08:01
@SuperFola: Does this issue only arise with `size_t` in specific..? or can you reproduce it with any type?

**Comment by SuperFola** [comment] 2018-02-12 14:17
Using size_t or uint32_t seems to be a problem, I can try others things (it seems to be a problem only with unsigned integers type) if you want :)

**Comment by mpark** [comment] 2019-01-14 15:47
I'm going to close this for now since MinGW is not a distro that I'm officially supporting at this point. If there are enough requests for MinGW support going forward, I'll perhaps invest more time.

**Closed** 2019-01-15 22:34 UTC
